"""replace role_id with admin field in user model

Revision ID: 0feb17e8c793
Revises: 31ee1b60a946
Create Date: 2025-03-31 11:20:24.763705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0feb17e8c793'
down_revision: Union[str, None] = '31ee1b60a946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
